test = {   'name': 'q6_1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(nonbinary_prop_marvel, float)\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> not np.isclose(nonbinary_prop_marvel, 0.0028700537371763556) # Close, but not quite! Only look at characters where data is available.\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
