test = {   'name': 'q3_1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> callable(get_abbr)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> callable(get_meaning)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> type(get_abbr("YOLO: You only live once")) == str\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> type(get_meaning("YOLO: You only live once")) == str\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> get_meaning("YOLO: You only live once")[0] != \' \' # Your meaning string should not start with a space.\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
