test = {   'name': 'q3_5',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> import numbers;\n>>> isinstance(longest_avg_name_length, float) or isinstance(longest_avg_name_length, numbers.Integral)\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> import numbers;\n>>> isinstance(shortest_avg_name_length, float) or isinstance(shortest_avg_name_length, numbers.Integral)\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> import numbers;\n>>> isinstance(range_avg_name_length, float) or isinstance(range_avg_name_length, numbers.Integral)\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
